<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
        Schema::enableForeignKeyConstraints();

        $countries = array(
            array('code' => 'AF', 'name' => 'Afghanistan', 'area_code' => '93'),
            array('code' => 'AL', 'name' => 'Albania', 'area_code' => '355'),
            array('code' => 'DZ', 'name' => 'Algeria', 'area_code' => '213'),
            array('code' => 'AS', 'name' => 'American Samoa', 'area_code' => '1-684'),
            array('code' => 'AD', 'name' => 'Andorra', 'area_code' => '376'),
            array('code' => 'AO', 'name' => 'Angola', 'area_code' => '244'),
            array('code' => 'AI', 'name' => 'Anguilla', 'area_code' => '1-264'),
            array('code' => 'AQ', 'name' => 'Antarctica', 'area_code' => '672'),
            array('code' => 'AG', 'name' => 'Antigua and/or Barbuda', 'area_code' => '1-268'),
            array('code' => 'AR', 'name' => 'Argentina', 'area_code' => '54'),
            array('code' => 'AM', 'name' => 'Armenia', 'area_code' => '374'),
            array('code' => 'AW', 'name' => 'Aruba', 'area_code' => '297'),
            array('code' => 'AU', 'name' => 'Australia', 'area_code' => '61'),
            array('code' => 'AT', 'name' => 'Austria', 'area_code' => '43'),
            array('code' => 'AZ', 'name' => 'Azerbaijan', 'area_code' => '994'),
            array('code' => 'BS', 'name' => 'Bahamas', 'area_code' => '1-242'),
            array('code' => 'BH', 'name' => 'Bahrain', 'area_code' => '973'),
            array('code' => 'BD', 'name' => 'Bangladesh', 'area_code' => '880'),
            array('code' => 'BB', 'name' => 'Barbados', 'area_code' => '1-246'),
            array('code' => 'BY', 'name' => 'Belarus', 'area_code' => '375'),
            array('code' => 'BE', 'name' => 'Belgium', 'area_code' => '32'),
            array('code' => 'BZ', 'name' => 'Belize', 'area_code' => '501'),
            array('code' => 'BJ', 'name' => 'Benin', 'area_code' => '229'),
            array('code' => 'BM', 'name' => 'Bermuda', 'area_code' => '1-441'),
            array('code' => 'BT', 'name' => 'Bhutan', 'area_code' => '975'),
            array('code' => 'BO', 'name' => 'Bolivia', 'area_code' => '591'),
            array('code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'area_code' => '387'),
            array('code' => 'BW', 'name' => 'Botswana', 'area_code' => '267'),
            array('code' => 'BV', 'name' => 'Bouvet Island', 'area_code' => '0'),
            array('code' => 'BR', 'name' => 'Brazil', 'area_code' => '55'),
            array('code' => 'IO', 'name' => 'British lndian Ocean Territory', 'area_code' => '246'),
            array('code' => 'BN', 'name' => 'Brunei Darussalam', 'area_code' => '673'),
            array('code' => 'BG', 'name' => 'Bulgaria', 'area_code' => '359'),
            array('code' => 'BF', 'name' => 'Burkina Faso', 'area_code' => '226'),
            array('code' => 'BI', 'name' => 'Burundi', 'area_code' => '257'),
            array('code' => 'CA', 'name' => 'Canada', 'area_code' => '1'),
            array('code' => 'KH', 'name' => 'Cambodia', 'area_code' => '855'),
            array('code' => 'CM', 'name' => 'Cameroon', 'area_code' => '237'),
            array('code' => 'CV', 'name' => 'Cape Verde', 'area_code' => '238'),
            array('code' => 'KY', 'name' => 'Cayman Islands', 'area_code' => '1-345'),
            array('code' => 'CF', 'name' => 'Central African Republic', 'area_code' => '236'),
            array('code' => 'TD', 'name' => 'Chad', 'area_code' => '235'),
            array('code' => 'CL', 'name' => 'Chile', 'area_code' => '56'),
            array('code' => 'CN', 'name' => 'China', 'area_code' => '86'),
            array('code' => 'CX', 'name' => 'Christmas Island', 'area_code' => '61'),
            array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'area_code' => '61'),
            array('code' => 'CO', 'name' => 'Colombia', 'area_code' => '57'),
            array('code' => 'KM', 'name' => 'Comoros', 'area_code' => '269'),
            array('code' => 'CG', 'name' => 'Congo', 'area_code' => '242'),
            array('code' => 'CK', 'name' => 'Cook Islands', 'area_code' => '682'),
            array('code' => 'CR', 'name' => 'Costa Rica', 'area_code' => '506'),
            array('code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'area_code' => '385'),
            array('code' => 'CU', 'name' => 'Cuba', 'area_code' => '53'),
            array('code' => 'CY', 'name' => 'Cyprus', 'area_code' => '357'),
            array('code' => 'CZ', 'name' => 'Czech Republic', 'area_code' => '420'),
            array('code' => 'CD', 'name' => 'Democratic Republic of Congo', 'area_code' => '243'),
            array('code' => 'DK', 'name' => 'Denmark', 'area_code' => '45'),
            array('code' => 'DJ', 'name' => 'Djibouti', 'area_code' => '253'),
            array('code' => 'DM', 'name' => 'Dominica', 'area_code' => '1-767'),
            array('code' => 'DO', 'name' => 'Dominican Republic', 'area_code' => '1-809'),
            array('code' => 'TP', 'name' => 'East Timor', 'area_code' => '670'),
            array('code' => 'EC', 'name' => 'Ecudaor', 'area_code' => '593'),
            array('code' => 'EG', 'name' => 'Egypt', 'area_code' => '20'),
            array('code' => 'SV', 'name' => 'El Salvador', 'area_code' => '503'),
            array('code' => 'GQ', 'name' => 'Equatorial Guinea', 'area_code' => '240'),
            array('code' => 'ER', 'name' => 'Eritrea', 'area_code' => '291'),
            array('code' => 'EE', 'name' => 'Estonia', 'area_code' => '372'),
            array('code' => 'ET', 'name' => 'Ethiopia', 'area_code' => '251'),
            array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'area_code' => '500'),
            array('code' => 'FO', 'name' => 'Faroe Islands', 'area_code' => '298'),
            array('code' => 'FJ', 'name' => 'Fiji', 'area_code' => '679'),
            array('code' => 'FI', 'name' => 'Finland', 'area_code' => '358'),
            array('code' => 'FR', 'name' => 'France', 'area_code' => '33'),
            array('code' => 'FX', 'name' => 'France, Metropolitan', 'area_code' => '33'),
            array('code' => 'GF', 'name' => 'French Guiana', 'area_code' => '33'),
            array('code' => 'PF', 'name' => 'French Polynesia', 'area_code' => '689'),
            array('code' => 'TF', 'name' => 'French Southern Territories', 'area_code' => '33'),
            array('code' => 'GA', 'name' => 'Gabon', 'area_code' => '241'),
            array('code' => 'GM', 'name' => 'Gambia', 'area_code' => '220'),
            array('code' => 'GE', 'name' => 'Georgia', 'area_code' => '995'),
            array('code' => 'DE', 'name' => 'Germany', 'area_code' => '49'),
            array('code' => 'GH', 'name' => 'Ghana', 'area_code' => '233'),
            array('code' => 'GI', 'name' => 'Gibraltar', 'area_code' => '350'),
            array('code' => 'GR', 'name' => 'Greece', 'area_code' => '30'),
            array('code' => 'GL', 'name' => 'Greenland', 'area_code' => '299'),
            array('code' => 'GD', 'name' => 'Grenada', 'area_code' => '1-473'),
            array('code' => 'GP', 'name' => 'Guadeloupe', 'area_code' => '0'),
            array('code' => 'GU', 'name' => 'Guam', 'area_code' => '1-671'),
            array('code' => 'GT', 'name' => 'Guatemala', 'area_code' => '502'),
            array('code' => 'GN', 'name' => 'Guinea', 'area_code' => '224'),
            array('code' => 'GW', 'name' => 'Guinea-Bissau', 'area_code' => '245'),
            array('code' => 'GY', 'name' => 'Guyana', 'area_code' => '592'),
            array('code' => 'HT', 'name' => 'Haiti', 'area_code' => '509'),
            array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'area_code' => '0'),
            array('code' => 'HN', 'name' => 'Honduras', 'area_code' => '504'),
            array('code' => 'HK', 'name' => 'Hong Kong', 'area_code' => '852'),
            array('code' => 'HU', 'name' => 'Hungary', 'area_code' => '36'),
            array('code' => 'IS', 'name' => 'Iceland', 'area_code' => '354'),
            array('code' => 'IN', 'name' => 'India', 'area_code' => '91'),
            array('code' => 'ID', 'name' => 'Indonesia', 'area_code' => '62'),
            array('code' => 'IR', 'name' => 'Iran (Islamic Republic of)', 'area_code' => '98'),
            array('code' => 'IQ', 'name' => 'Iraq', 'area_code' => '964'),
            array('code' => 'IE', 'name' => 'Ireland', 'area_code' => '353'),
            array('code' => 'IL', 'name' => 'Israel', 'area_code' => '972'),
            array('code' => 'IT', 'name' => 'Italy', 'area_code' => '39'),
            array('code' => 'CI', 'name' => 'Ivory Coast', 'area_code' => '225'),
            array('code' => 'JM', 'name' => 'Jamaica', 'area_code' => '1-876'),
            array('code' => 'JP', 'name' => 'Japan', 'area_code' => '81'),
            array('code' => 'JO', 'name' => 'Jordan', 'area_code' => '962'),
            array('code' => 'KZ', 'name' => 'Kazakhstan', 'area_code' => '7'),
            array('code' => 'KE', 'name' => 'Kenya', 'area_code' => '254'),
            array('code' => 'KI', 'name' => 'Kiribati', 'area_code' => '686'),
            array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'area_code' => '850'),
            array('code' => 'KR', 'name' => 'Korea, Republic of', 'area_code' => '82'),
            array('code' => 'KW', 'name' => 'Kuwait', 'area_code' => '965'),
            array('code' => 'KG', 'name' => 'Kyrgyzstan', 'area_code' => '996'),
            array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'area_code' => '856'),
            array('code' => 'LV', 'name' => 'Latvia', 'area_code' => '371'),
            array('code' => 'LB', 'name' => 'Lebanon', 'area_code' => '961'),
            array('code' => 'LS', 'name' => 'Lesotho', 'area_code' => '266'),
            array('code' => 'LR', 'name' => 'Liberia', 'area_code' => '231'),
            array('code' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'area_code' => '218'),
            array('code' => 'LI', 'name' => 'Liechtenstein', 'area_code' => '423'),
            array('code' => 'LT', 'name' => 'Lithuania', 'area_code' => '370'),
            array('code' => 'LU', 'name' => 'Luxembourg', 'area_code' => '352'),
            array('code' => 'MO', 'name' => 'Macau', 'area_code' => '853'),
            array('code' => 'MK', 'name' => 'Macedonia', 'area_code' => '389'),
            array('code' => 'MG', 'name' => 'Madagascar', 'area_code' => '261'),
            array('code' => 'MW', 'name' => 'Malawi', 'area_code' => '265'),
            array('code' => 'MY', 'name' => 'Malaysia', 'area_code' => '60'),
            array('code' => 'MV', 'name' => 'Maldives', 'area_code' => '960'),
            array('code' => 'ML', 'name' => 'Mali', 'area_code' => '223'),
            array('code' => 'MT', 'name' => 'Malta', 'area_code' => '356'),
            array('code' => 'MH', 'name' => 'Marshall Islands', 'area_code' => '692'),
            array('code' => 'MQ', 'name' => 'Martinique', 'area_code' => '0'),
            array('code' => 'MR', 'name' => 'Mauritania', 'area_code' => '222'),
            array('code' => 'MU', 'name' => 'Mauritius', 'area_code' => '230'),
            array('code' => 'TY', 'name' => 'Mayotte', 'area_code' => '262'),
            array('code' => 'MX', 'name' => 'Mexico', 'area_code' => '52'),
            array('code' => 'FM', 'name' => 'Micronesia, Federated States of', 'area_code' => '691'),
            array('code' => 'MD', 'name' => 'Moldova, Republic of', 'area_code' => '373'),
            array('code' => 'MC', 'name' => 'Monaco', 'area_code' => '377'),
            array('code' => 'MN', 'name' => 'Mongolia', 'area_code' => '976'),
            array('code' => 'MS', 'name' => 'Montserrat', 'area_code' => '1-664'),
            array('code' => 'MA', 'name' => 'Morocco', 'area_code' => '212'),
            array('code' => 'MZ', 'name' => 'Mozambique', 'area_code' => '258'),
            array('code' => 'MM', 'name' => 'Myanmar', 'area_code' => '95'),
            array('code' => 'NA', 'name' => 'Namibia', 'area_code' => '264'),
            array('code' => 'NR', 'name' => 'Nauru', 'area_code' => '674'),
            array('code' => 'NP', 'name' => 'Nepal', 'area_code' => '977'),
            array('code' => 'NL', 'name' => 'Netherlands', 'area_code' => '31'),
            array('code' => 'AN', 'name' => 'Netherlands Antilles', 'area_code' => '599'),
            array('code' => 'NC', 'name' => 'New Caledonia', 'area_code' => '687'),
            array('code' => 'NZ', 'name' => 'New Zealand', 'area_code' => '64'),
            array('code' => 'NI', 'name' => 'Nicaragua', 'area_code' => '505'),
            array('code' => 'NE', 'name' => 'Niger', 'area_code' => '227'),
            array('code' => 'NG', 'name' => 'Nigeria', 'area_code' => '234'),
            array('code' => 'NU', 'name' => 'Niue', 'area_code' => '683'),
            array('code' => 'NF', 'name' => 'Norfork Island', 'area_code' => '0'),
            array('code' => 'MP', 'name' => 'Northern Mariana Islands', 'area_code' => '1-670'),
            array('code' => 'NO', 'name' => 'Norway', 'area_code' => '47'),
            array('code' => 'OM', 'name' => 'Oman', 'area_code' => '968'),
            array('code' => 'PK', 'name' => 'Pakistan', 'area_code' => '92'),
            array('code' => 'PW', 'name' => 'Palau', 'area_code' => '680'),
            array('code' => 'PA', 'name' => 'Panama', 'area_code' => '507'),
            array('code' => 'PG', 'name' => 'Papua New Guinea', 'area_code' => '675'),
            array('code' => 'PY', 'name' => 'Paraguay', 'area_code' => '595'),
            array('code' => 'PE', 'name' => 'Peru', 'area_code' => '51'),
            array('code' => 'PH', 'name' => 'Philippines', 'area_code' => '63'),
            array('code' => 'PN', 'name' => 'Pitcairn', 'area_code' => '64'),
            array('code' => 'PL', 'name' => 'Poland', 'area_code' => '48'),
            array('code' => 'PT', 'name' => 'Portugal', 'area_code' => '351'),
            array('code' => 'PR', 'name' => 'Puerto Rico', 'area_code' => '1-787'),
            array('code' => 'QA', 'name' => 'Qatar', 'area_code' => '974'),
            array('code' => 'SS', 'name' => 'Republic of South Sudan', 'area_code' => '211'),
            array('code' => 'RE', 'name' => 'Reunion', 'area_code' => '262'),
            array('code' => 'RO', 'name' => 'Romania', 'area_code' => '40'),
            array('code' => 'RU', 'name' => 'Russian Federation', 'area_code' => '7'),
            array('code' => 'RW', 'name' => 'Rwanda', 'area_code' => '250'),
            array('code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'area_code' => '1-869'),
            array('code' => 'LC', 'name' => 'Saint Lucia', 'area_code' => '1-758'),
            array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'area_code' => '1-784'),
            array('code' => 'WS', 'name' => 'Samoa', 'area_code' => '685'),
            array('code' => 'SM', 'name' => 'San Marino', 'area_code' => '378'),
            array('code' => 'ST', 'name' => 'Sao Tome and Principe', 'area_code' => '239'),
            array('code' => 'SA', 'name' => 'Saudi Arabia', 'area_code' => '966'),
            array('code' => 'SN', 'name' => 'Senegal', 'area_code' => '221'),
            array('code' => 'RS', 'name' => 'Serbia', 'area_code' => '381'),
            array('code' => 'SC', 'name' => 'Seychelles', 'area_code' => '248'),
            array('code' => 'SL', 'name' => 'Sierra Leone', 'area_code' => '232'),
            array('code' => 'SG', 'name' => 'Singapore', 'area_code' => '65'),
            array('code' => 'SK', 'name' => 'Slovakia', 'area_code' => '421'),
            array('code' => 'SI', 'name' => 'Slovenia', 'area_code' => '386'),
            array('code' => 'SB', 'name' => 'Solomon Islands', 'area_code' => '677'),
            array('code' => 'SO', 'name' => 'Somalia', 'area_code' => '252'),
            array('code' => 'ZA', 'name' => 'South Africa', 'area_code' => '27'),
            array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands', 'area_code' => '0'),
            array('code' => 'ES', 'name' => 'Spain', 'area_code' => '34'),
            array('code' => 'LK', 'name' => 'Sri Lanka', 'area_code' => '94'),
            array('code' => 'SH', 'name' => 'St. Helena', 'area_code' => '290'),
            array('code' => 'PM', 'name' => 'St. Pierre and Miquelon', 'area_code' => '508'),
            array('code' => 'SD', 'name' => 'Sudan', 'area_code' => '249'),
            array('code' => 'SR', 'name' => 'Suriname', 'area_code' => '597'),
            array('code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands', 'area_code' => '47'),
            array('code' => 'SZ', 'name' => 'Swaziland', 'area_code' => '268'),
            array('code' => 'SE', 'name' => 'Sweden', 'area_code' => '46'),
            array('code' => 'CH', 'name' => 'Switzerland', 'area_code' => '41'),
            array('code' => 'SY', 'name' => 'Syrian Arab Republic', 'area_code' => '963'),
            array('code' => 'TW', 'name' => 'Taiwan', 'area_code' => '886'),
            array('code' => 'TJ', 'name' => 'Tajikistan', 'area_code' => '992'),
            array('code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'area_code' => '255'),
            array('code' => 'TH', 'name' => 'Thailand', 'area_code' => '66'),
            array('code' => 'TG', 'name' => 'Togo', 'area_code' => '228'),
            array('code' => 'TK', 'name' => 'Tokelau', 'area_code' => '690'),
            array('code' => 'TO', 'name' => 'Tonga', 'area_code' => '676'),
            array('code' => 'TT', 'name' => 'Trinidad and Tobago', 'area_code' => '1-686'),
            array('code' => 'TN', 'name' => 'Tunisia', 'area_code' => '216'),
            array('code' => 'TR', 'name' => 'Turkey', 'area_code' => '90'),
            array('code' => 'TM', 'name' => 'Turkmenistan', 'area_code' => '993'),
            array('code' => 'TC', 'name' => 'Turks and Caicos Islands', 'area_code' => '1-649'),
            array('code' => 'TV', 'name' => 'Tuvalu', 'area_code' => '688'),
            array('code' => 'UG', 'name' => 'Uganda', 'area_code' => '256'),
            array('code' => 'UA', 'name' => 'Ukraine', 'area_code' => '380'),
            array('code' => 'AE', 'name' => 'United Arab Emirates', 'area_code' => '971'),
            array('code' => 'GB', 'name' => 'United Kingdom', 'area_code' => '44'),
            array('code' => 'US', 'name' => 'United States', 'area_code' => '1'),
            array('code' => 'UM', 'name' => 'United States minor outlying islands', 'area_code' => '0'),
            array('code' => 'UY', 'name' => 'Uruguay', 'area_code' => '598'),
            array('code' => 'UZ', 'name' => 'Uzbekistan', 'area_code' => '998'),
            array('code' => 'VU', 'name' => 'Vanuatu', 'area_code' => '678'),
            array('code' => 'VA', 'name' => 'Vatican City State', 'area_code' => '379'),
            array('code' => 'VE', 'name' => 'Venezuela', 'area_code' => '58'),
            array('code' => 'VN', 'name' => 'Vietnam', 'area_code' => '84'),
            array('code' => 'VG', 'name' => 'Virgin Islands (British)', 'area_code' => '1-284'),
            array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'area_code' => '1-340'),
            array('code' => 'WF', 'name' => 'Wallis and Futuna Islands', 'area_code' => '681'),
            array('code' => 'EH', 'name' => 'Western Sahara', 'area_code' => '212'),
            array('code' => 'YE', 'name' => 'Yemen', 'area_code' => '967'),
            array('code' => 'YU', 'name' => 'Yugoslavia', 'area_code' => '0'),
            array('code' => 'ZR', 'name' => 'Zaire', 'area_code' => '0'),
            array('code' => 'ZM', 'name' => 'Zambia', 'area_code' => '260'),
            array('code' => 'ZW', 'name' => 'Zimbabwe', 'area_code' => '263'),
        );

        DB::table('countries')->insert($countries);
    }
}
