<?php

use Illuminate\Database\Seeder;

class CountryCodeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('country_codes')->truncate();
        Schema::enableForeignKeyConstraints();

        $countriesCodes = array(
            array('code' => '93', 'name' => '+93 Afghanistan'),
            array('code' => '355', 'name' => '+355 Albania'),
            array('code' => '213', 'name' => '+213 Algeria'),
            array('code' => '1684', 'name' => '+1 684 American Samoa'),
            array('code' => '376', 'name' => '+376 Andorra'),
            array('code' => '244', 'name' => '+244 Angola'),
            array('code' => '1264', 'name' => '+1 264 Anguilla'),
            array('code' => '6721', 'name' => '+6721 Antarctica'),
            array('code' => '1268', 'name' => '+1 268 Antigua and/or Barbuda'),
            array('code' => '54', 'name' => '+54 Argentina'),
            array('code' => '374', 'name' => '+374 Armenia'),
            array('code' => '297', 'name' => '+297 Aruba'),
            array('code' => '61', 'name' => '+61 Australia'),
            array('code' => '43', 'name' => '+43 Austria'),
            array('code' => '994', 'name' => '+994 Azerbaijan'),
            array('code' => '1242', 'name' => '+1 242 Bahamas'),
            array('code' => '973', 'name' => '+973 Bahrain'),
            array('code' => '880', 'name' => '+880 Bangladesh'),
            array('code' => '1246', 'name' => '+1 246 Barbados'),
            array('code' => '375', 'name' => '+375 Belarus'),
            array('code' => '32', 'name' => '+32 Belgium'),
            array('code' => '501', 'name' => '+501 Belize'),
            array('code' => '501', 'name' => '+501 Benin'),
            array('code' => '1441', 'name' => '+1 441 Bermuda'),
            array('code' => '975', 'name' => '+975 Bhutan'),
            array('code' => '591', 'name' => '+591 Bolivia'),
            array('code' => '387', 'name' => '+387 Bosnia and Herzegovina'),
            array('code' => '267', 'name' => '+267 Botswana'),
            array('code' => '55', 'name' => '+55 Bouvet Island'),
            array('code' => '55', 'name' => '+55 Brazil'),
            array('code' => '246', 'name' => '+246 British lndian Ocean Territory'),
            array('code' => '673', 'name' => '+673 Brunei Darussalam'),
            array('code' => '359', 'name' => '+359 Bulgaria'),
            array('code' => '226', 'name' => '+226 Burkina Faso'),
            array('code' => '257', 'name' => '+257 Burundi'),
            array('code' => '1', 'name' => '+1 Canada'),
            array('code' => '855', 'name' => '+855 Cambodia'),
            array('code' => '237', 'name' => '+237 Cameroon'),
            array('code' => '238', 'name' => '+238 Cape Verde'),
            array('code' => '1345', 'name' => '+1 345 Cayman Islands'),
            array('code' => '236', 'name' => '+236 Central African Republic'),
            array('code' => '235', 'name' => '+235 Chad'),
            array('code' => '56', 'name' => '+56 Chile'),
            array('code' => '86', 'name' => '+86 China'),
            array('code' => '61', 'name' => '+61 Christmas Island'),
            array('code' => '682', 'name' => '+682 Cocos (Keeling) Islands'),
            array('code' => '57', 'name' => '+57 Colombia'),
            array('code' => '269', 'name' => '+269 Comoros'),
            array('code' => '243', 'name' => '+243 Congo'),
            array('code' => '682', 'name' => '+682 Cook Islands'),
            array('code' => '506', 'name' => '+506 Costa Rica'),
            array('code' => '385', 'name' => '+385 Croatia (Hrvatska)'),
            array('code' => '53', 'name' => '+53 Cuba'),
            array('code' => '357', 'name' => '+357 Cyprus'),
            array('code' => '420', 'name' => '+420 Czech Republic'),
            array('code' => '1809', 'name' => '+1 809 Democratic Republic of Congo'),
            array('code' => '45', 'name' => '+45 Denmark'),
            array('code' => '253', 'name' => '+253 Djibouti'),
            array('code' => '253', 'name' => '+253 Dominica'),
            array('code' => '1829', 'name' => '+1 829 Dominican Republic'),
            array('code' => '670', 'name' => '+670 East Timor'),
            array('code' => '593', 'name' => '+593 Ecudaor'),
            array('code' => '20', 'name' => '+20 Egypt'),
            array('code' => '503', 'name' => '+503 El Salvador'),
            array('code' => '240', 'name' => '+240 Equatorial Guinea'),
            array('code' => '291', 'name' => '+291 Eritrea'),
            array('code' => '372', 'name' => '+372 Estonia'),
            array('code' => '251', 'name' => '+251 Ethiopia'),
            array('code' => '500', 'name' => '+500 Falkland Islands (Malvinas)'),
            array('code' => '298', 'name' => '+298 Faroe Islands'),
            array('code' => '679', 'name' => '+679 Fiji'),
            array('code' => '358', 'name' => '+358 Finland'),
            array('code' => '33', 'name' => '+33 France'),
            array('code' => '33', 'name' => '+33 France, Metropolitan'),
            array('code' => '594', 'name' => '+594 French Guiana'),
            array('code' => '689', 'name' => '+689 French Polynesia'),
            array('code' => '262', 'name' => '+262 French Southern Territories'),
            array('code' => '241', 'name' => '+241 Gabon'),
            array('code' => '220', 'name' => '+220 Gambia'),
            array('code' => '995', 'name' => '+995 Georgia'),
            array('code' => '49', 'name' => '+49 Germany'),
            array('code' => '233', 'name' => '+233 Ghana'),
            array('code' => '350', 'name' => '+350 Gibraltar'),
            array('code' => '30', 'name' => '+30 Greece'),
            array('code' => '299', 'name' => '+299 Greenland'),
            array('code' => '1473', 'name' => '+1 473 Grenada'),
            array('code' => '590', 'name' => '+590 Guadeloupe'),
            array('code' => '1671', 'name' => '+1 671 Guam'),
            array('code' => '502', 'name' => '+502 Guatemala'),
            array('code' => '224', 'name' => '+224 Guinea'),
            array('code' => '245', 'name' => '+245 Guinea-Bissau'),
            array('code' => '592', 'name' => '+592 Guyana'),
            array('code' => '509', 'name' => '+509 Haiti'),
            array('code' => '0', 'name' => '+0 Heard and Mc Donald Islands'),
            array('code' => '504', 'name' => '+504 Honduras'),
            array('code' => '852', 'name' => '+852 Hong Kong'),
            array('code' => '36', 'name' => '+36 Hungary'),
            array('code' => '354', 'name' => '+354 Iceland'),
            array('code' => '91', 'name' => '+91 India'),
            array('code' => '62', 'name' => '+62 Indonesia'),
            array('code' => '98', 'name' => '+98 Iran (Islamic Republic of)'),
            array('code' => '964', 'name' => '+964 Iraq'),
            array('code' => '353', 'name' => '+353 Ireland'),
            array('code' => '972', 'name' => '+972 Israel'),
            array('code' => '39', 'name' => '+39 Italy'),
            array('code' => '225', 'name' => '+225 Ivory Coast'),
            array('code' => '1876', 'name' => '+1 876 Jamaica'),
            array('code' => '81', 'name' => '+81 Japan'),
            array('code' => '962', 'name' => '+962 Jordan'),
            array('code' => '7', 'name' => '+7 Kazakhstan'),
            array('code' => '254', 'name' => '+254 Kenya'),
            array('code' => '686', 'name' => '+686 Kiribati'),
            array('code' => '850', 'name' => '+850 Korea, Democratic People\'s Republic of'),
            array('code' => '82', 'name' => '+82 Korea, Republic of'),
            array('code' => '965', 'name' => '+965 Kuwait'),
            array('code' => '996', 'name' => '+996 Kyrgyzstan'),
            array('code' => '856', 'name' => '+856 Lao People\'s Democratic Republic'),
            array('code' => '371', 'name' => '+371 Latvia'),
            array('code' => '961', 'name' => '+961 Lebanon'),
            array('code' => '266', 'name' => '+266 Lesotho'),
            array('code' => '231', 'name' => '+231 Liberia'),
            array('code' => '218', 'name' => '+218 Libyan Arab Jamahiriya'),
            array('code' => '423', 'name' => '+423 Liechtenstein'),
            array('code' => '370', 'name' => '+370 Lithuania'),
            array('code' => '352', 'name' => '+352 Luxembourg'),
            array('code' => '853', 'name' => '+853 Macau'),
            array('code' => '389', 'name' => '+389 Macedonia'),
            array('code' => '261', 'name' => '+261 Madagascar'),
            array('code' => '265', 'name' => '+265 Malawi'),
            array('code' => '60', 'name' => '+60 Malaysia'),
            array('code' => '960', 'name' => '+960 Maldives'),
            array('code' => '223', 'name' => '+223 Mali'),
            array('code' => '356', 'name' => '+356 Malta'),
            array('code' => '692', 'name' => '+692 Marshall Islands'),
            array('code' => '596', 'name' => '+596 Martinique'),
            array('code' => '222', 'name' => '+222 Mauritania'),
            array('code' => '230', 'name' => '+230 Mauritius'),
            array('code' => '262', 'name' => '+262 Mayotte'),
            array('code' => '52', 'name' => '+52 Mexico'),
            array('code' => '691', 'name' => '+691 Micronesia, Federated States of'),
            array('code' => '373', 'name' => '+373 Moldova, Republic of'),
            array('code' => '377', 'name' => '+377 Monaco'),
            array('code' => '976', 'name' => '+976 Mongolia'),
            array('code' => '1664', 'name' => '+1 664 Montserrat'),
            array('code' => '212', 'name' => '+212 Morocco'),
            array('code' => '258', 'name' => '+258 Mozambique'),
            array('code' => '95', 'name' => '+95 Myanmar'),
            array('code' => '264', 'name' => '+264 Namibia'),
            array('code' => '674', 'name' => '+674 Nauru'),
            array('code' => '977', 'name' => '+977 Nepal'),
            array('code' => '31', 'name' => '+31 Netherlands'),
            array('code' => '599', 'name' => '+599 Netherlands Antilles'),
            array('code' => '687', 'name' => '+687 New Caledonia'),
            array('code' => '64', 'name' => '+64 New Zealand'),
            array('code' => '505', 'name' => '+505 Nicaragua'),
            array('code' => '227', 'name' => '+227 Niger'),
            array('code' => '234', 'name' => '234 Nigeria'),
            array('code' => '683', 'name' => '+683 Niue'),
            array('code' => '6723', 'name' => '+6723 Norfork Island'),
            array('code' => '1670', 'name' => '+1 670 Northern Mariana Islands'),
            array('code' => '47', 'name' => '+47 Norway'),
            array('code' => '968', 'name' => '+968 Oman'),
            array('code' => '92', 'name' => '+92 Pakistan'),
            array('code' => '680', 'name' => '+680 Palau'),
            array('code' => '507', 'name' => '+507 Panama'),
            array('code' => '675', 'name' => '+675 Papua New Guinea'),
            array('code' => '595', 'name' => '+595 Paraguay'),
            array('code' => '51', 'name' => '+51 Peru'),
            array('code' => '63', 'name' => '+63 Philippines'),
            array('code' => '64', 'name' => '+64 Pitcairn'),
            array('code' => '48', 'name' => '+48 Poland'),
            array('code' => '351', 'name' => '+351 Portugal'),
            array('code' => '1787', 'name' => '+1 787 Puerto Rico'),
            array('code' => '974', 'name' => '+974 Qatar'),
            array('code' => '211', 'name' => '+211 Republic of South Sudan'),
            array('code' => '262', 'name' => '+262 Reunion'),
            array('code' => '40', 'name' => '+40 Romania'),
            array('code' => '7', 'name' => '+7 Russian Federation'),
            array('code' => '250', 'name' => '+250 Rwanda'),
            array('code' => '1869', 'name' => '+1 869 Saint Kitts and Nevis'),
            array('code' => '1758', 'name' => '+1 758 Saint Lucia'),
            array('code' => '1784', 'name' => '+1 784 Saint Vincent and the Grenadines'),
            array('code' => '685', 'name' => '+685 Samoa'),
            array('code' => '378', 'name' => '+378 San Marino'),
            array('code' => '239', 'name' => '+239 Sao Tome and Principe'),
            array('code' => '966', 'name' => '+966 Saudi Arabia'),
            array('code' => '221', 'name' => '+221 Senegal'),
            array('code' => '381', 'name' => '+381 Serbia'),
            array('code' => '248', 'name' => '+248 Seychelles'),
            array('code' => '232', 'name' => '+232 Sierra Leone'),
            array('code' => '65', 'name' => '+65 Singapore'),
            array('code' => '421', 'name' => '+421 Slovakia'),
            array('code' => '386', 'name' => '+386 Slovenia'),
            array('code' => '677', 'name' => '+677 Solomon Islands'),
            array('code' => '252', 'name' => '+252 Somalia'),
            array('code' => '27', 'name' => '+27 South Africa'),
            array('code' => '500', 'name' => '+500 South Georgia South Sandwich Islands'),
            array('code' => '34', 'name' => '+34 Spain'),
            array('code' => '94', 'name' => '+94 Sri Lanka'),
            array('code' => '290', 'name' => '+290 St. Helena'),
            array('code' => '508', 'name' => '+508 St. Pierre and Miquelon'),
            array('code' => '249', 'name' => '+249 Sudan'),
            array('code' => '597', 'name' => '+597 Suriname'),
            array('code' => '47', 'name' => '+47 Svalbarn and Jan Mayen Islands'),
            array('code' => '268', 'name' => '+268 Swaziland'),
            array('code' => '46', 'name' => '+46 Sweden'),
            array('code' => '41', 'name' => '+41 Switzerland'),
            array('code' => '963', 'name' => '+963 Syrian Arab Republic'),
            array('code' => '886', 'name' => '+886 Taiwan'),
            array('code' => '992', 'name' => '+992 Tajikistan'),
            array('code' => '255', 'name' => '+255 Tanzania, United Republic of'),
            array('code' => '66', 'name' => '+66 Thailand'),
            array('code' => '228', 'name' => '+228 Togo'),
            array('code' => '690', 'name' => '+690 Tokelau'),
            array('code' => '676', 'name' => '+676 Tonga'),
            array('code' => '1868', 'name' => '+1 868 Trinidad and Tobago'),
            array('code' => '216', 'name' => '+216 Tunisia'),
            array('code' => '90', 'name' => '+90 Turkey'),
            array('code' => '993', 'name' => '+993 Turkmenistan'),
            array('code' => '1649', 'name' => '+1 649 Turks and Caicos Islands'),
            array('code' => '688', 'name' => '+688 Tuvalu'),
            array('code' => '256', 'name' => '+256 Uganda'),
            array('code' => '380', 'name' => '+380 Ukraine'),
            array('code' => '971', 'name' => '+971 United Arab Emirates'),
            array('code' => '44', 'name' => '+44 United Kingdom'),
            array('code' => '1', 'name' => '+1 United States'),
            array('code' => '1', 'name' => '+1 United States minor outlying islands'),
            array('code' => '598', 'name' => '+598 Uruguay'),
            array('code' => '998', 'name' => '+998 Uzbekistan'),
            array('code' => '678', 'name' => '+678 Vanuatu'),
            array('code' => '379', 'name' => '+379 Vatican City State'),
            array('code' => '58', 'name' => '+58 Venezuela'),
            array('code' => '84', 'name' => '+84 Vietnam'),
            array('code' => '1', 'name' => '+1 Virgin Islands (British)'),
            array('code' => '1340', 'name' => '+1 340 Virgin Islands (U.S.)'),
            array('code' => '681', 'name' => '+681 Wallis and Futuna Islands'),
            array('code' => '212', 'name' => '+212 Western Sahara'),
            array('code' => '967', 'name' => '+967 Yemen'),
            array('code' => '38', 'name' => '+38 Yugoslavia'),
            array('code' => '243', 'name' => '+243 Zaire'),
            array('code' => '260', 'name' => '+260 Zambia'),
            array('code' => '263', 'name' => '+263 Zimbabwe'),
        );

        DB::table('country_codes')->insert($countriesCodes);
    }
}
